services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: vetdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vetdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    command: python -m flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "15000:5000"
    depends_on:
      db:
        condition: service_healthy 